const printName = (name) => {
  console.log('Name:', name);
  // What happens if this function is throwing an error?
};

printName('Sponge Bob');
